export const JobInformation = [
  {
    id: '1',
    employerDetails:
      'is a fast-growing company that relies on emerging technology talent, and we want to give you your first start. BestTech provides all its entry-level software developers with a paid training program to ensure you’ll learn the skills you need to succeed. We offer a flexible schedule and the opportunity to work with some of the industry’s best software developers, either in our Salt Lake City office or remotely across the world. With our wide range of Fortune 500 enterprises as clients, you’ll be working on projects that matter as a part of the BestTech team.',
    title: 'React Native Developer',
    location: 'Mumbai',
    vancancy: '2',
    companyName: 'Vistara Pvt Ltd.',
    companyLogo: require('../assets/CompanyLogo/CompanyLogo1.webp'),
    jobDescription:
      'We are looking for a great JavaScript developer who is proficient with React.js. Your primary focus will be on developing user interface components and implementing them following well-known React.js workflows (such as Flux or Redux). You will ensure that these components and the overall application are robust and easy to maintain. You will coordinate with the rest of the team working on different layers of the infrastructure. Therefore, a commitment to collaborative problem solving, sophisticated design, and quality product is important.',
    elligibiltyCriteria: {
      title: 'Bachelor of Technology/Engine',
      nationality: 'Indian',
      gender: 'Any',
    },
    industryType: 'IT-Software Services',
    functionalArea: 'IT-Softwre',
    KeySkills: 'React Native & TypeScript/JavaScript,Redux,Hooks,Navigations',
    employmenrType: 'Full Time',
    experienceDetails: '2-3 years',
    salary: '100k-200k',
    postedOn: '13 Nov',
  },
  {
    id: '2',
    employerDetails:
      'is a fast-growing company that relies on emerging technology talent, and we want to give you your first start. BestTech provides all its entry-level software developers with a paid training program to ensure you’ll learn the skills you need to succeed. We offer a flexible schedule and the opportunity to work with some of the industry’s best software developers, either in our Salt Lake City office or remotely across the world. With our wide range of Fortune 500 enterprises as clients, you’ll be working on projects that matter as a part of the BestTech team.',
    title: 'Wordpress Developer',
    location: 'Bhuwneshwar',
    vancancy: '2',
    companyName: 'Harness Digitech.',
    companyLogo: require('../assets/CompanyLogo/CompanyLogo2.png'),
    jobDescription:
      'We are looking for a great Wordpress developer who is proficient with Wordpress. Your primary focus will be on developing user interface components and implementing them following well-known React.js workflows (such as Flux or Redux). You will ensure that these components and the overall application are robust and easy to maintain. You will coordinate with the rest of the team working on different layers of the infrastructure. Therefore, a commitment to collaborative problem solving, sophisticated design, and quality product is important.',
    elligibiltyCriteria: {
      title: 'Bachelor of Technology/Engineering',
      nationality: 'Indian',
      gender: 'Any',
    },
    industryType: 'IT-Software Services',
    functionalArea: 'IT-Softwre',
    KeySkills: 'Wordpress & TypeScript/JavaScript,Redux',
    employmenrType: 'Full Time',
    experienceDetails: '2-5 years',
    salary: '100k-200k',
    postedOn: '1 Dec',
  },
  {
    id: '3',
    employerDetails:
      'is a fast-growing company that relies on emerging technology talent, and we want to give you your first start. BestTech provides all its entry-level software developers with a paid training program to ensure you’ll learn the skills you need to succeed. We offer a flexible schedule and the opportunity to work with some of the industry’s best software developers, either in our Salt Lake City office or remotely across the world. With our wide range of Fortune 500 enterprises as clients, you’ll be working on projects that matter as a part of the BestTech team.',
    title: 'Laravel Developer',
    location: 'Mumbai',
    vancancy: '2',
    companyName: 'MadeEasy Softwares.',
    companyLogo: require('../assets/CompanyLogo/CompanyLogo3.png'),
    jobDescription:
      'We are looking for a great Laravel developer who is proficient with Laravel. Your primary focus will be on developing user interface components and implementing them following well-known React.js workflows (such as Flux or Redux). You will ensure that these components and the overall application are robust and easy to maintain. You will coordinate with the rest of the team working on different layers of the infrastructure. Therefore, a commitment to collaborative problem solving, sophisticated design, and quality product is important.',
    elligibiltyCriteria: {
      title: 'Bachelor of Technology/Engineering',
      nationality: 'Indian',
      gender: 'Any',
    },
    industryType: 'IT-Software Services',
    functionalArea: 'IT-Softwre',
    KeySkills: 'Laravel , knowledge of DSA is plus',
    employmenrType: 'Full Time',
    experienceDetails: '0-5 years',
    salary: '100k-200k',
    postedOn: '23 Nov',
  },
  {
    id: '4',
    employerDetails:
      'is a fast-growing company that relies on emerging technology talent, and we want to give you your first start. BestTech provides all its entry-level software developers with a paid training program to ensure you’ll learn the skills you need to succeed. We offer a flexible schedule and the opportunity to work with some of the industry’s best software developers, either in our Salt Lake City office or remotely across the world. With our wide range of Fortune 500 enterprises as clients, you’ll be working on projects that matter as a part of the BestTech team.',
    title: 'React Developer',
    location: 'Mumbai',
    vancancy: '2',
    companyName: 'ClickKart Pvt Ltd.',
    companyLogo: require('../assets/CompanyLogo/CompanyLogo4.png'),
    jobDescription:
      'We are looking for a great JavaScript developer who is proficient with React.js. Your primary focus will be on developing user interface components and implementing them following well-known React.js workflows (such as Flux or Redux). You will ensure that these components and the overall application are robust and easy to maintain. You will coordinate with the rest of the team working on different layers of the infrastructure. Therefore, a commitment to collaborative problem solving, sophisticated design, and quality product is important.',
    elligibiltyCriteria: {
      title: 'Bachelor of Technology/Engineering',
      nationality: 'Indian',
      gender: 'Any',
    },
    industryType: 'IT-Software Services',
    functionalArea: 'IT-Softwre',
    KeySkills: 'React Native & TypeScript/JavaScript,Redux,Hooks,Navigations',
    employmenrType: 'Full Time',
    experienceDetails: '2-5 years',
    salary: '100k-200k',
    postedOn: '23 Jan',
  },
  {
    id: '5',
    employerDetails:
      'is a fast-growing company that relies on emerging technology talent, and we want to give you your first start. BestTech provides all its entry-level software developers with a paid training program to ensure you’ll learn the skills you need to succeed. We offer a flexible schedule and the opportunity to work with some of the industry’s best software developers, either in our Salt Lake City office or remotely across the world. With our wide range of Fortune 500 enterprises as clients, you’ll be working on projects that matter as a part of the BestTech team.',
    title: 'Angular Developer',
    location: 'Mumbai',
    vancancy: '2',
    companyName: 'Elexi Software solutions',
    companyLogo: require('../assets/CompanyLogo/CompanyLogo5.jpg'),
    jobDescription:
      'We are looking for a great Angular developer who is proficient with Angular. Your primary focus will be on developing user interface components and implementing them following well-known React.js workflows (such as Flux or Redux). You will ensure that these components and the overall application are robust and easy to maintain. You will coordinate with the rest of the team working on different layers of the infrastructure. Therefore, a commitment to collaborative problem solving, sophisticated design, and quality product is important.',
    elligibiltyCriteria: {
      title: 'Bachelor of Technology/Engineering',
      nationality: 'Indian',
      gender: 'Any',
    },
    industryType: 'IT-Software Services',
    functionalArea: 'IT-Softwre',
    KeySkills: 'Angular & TypeScript/JavaScript,Redux',
    employmenrType: 'Full Time',
    experienceDetails: '2-5 years',
    salary: '100k-200k',
    postedOn: '13 Aug',
  },
  {
    id: '6',
    employerDetails:
      'is a fast-growing company that relies on emerging technology talent, and we want to give you your first start. BestTech provides all its entry-level software developers with a paid training program to ensure you’ll learn the skills you need to succeed. We offer a flexible schedule and the opportunity to work with some of the industry’s best software developers, either in our Salt Lake City office or remotely across the world. With our wide range of Fortune 500 enterprises as clients, you’ll be working on projects that matter as a part of the BestTech team.',
    title: 'JavaScript Developer',
    location: 'Luckhnow',
    vancancy: '2',
    companyName: 'Purnima Pvt Ltd.',
    companyLogo: require('../assets/CompanyLogo/CompanyLogo6.png'),
    jobDescription:
      'We are looking for a great JavaScript developer who is proficient with React.js. Your primary focus will be on developing user interface components and implementing them following well-known React.js workflows (such as Flux or Redux). You will ensure that these components and the overall application are robust and easy to maintain. You will coordinate with the rest of the team working on different layers of the infrastructure. Therefore, a commitment to collaborative problem solving, sophisticated design, and quality product is important.',
    elligibiltyCriteria: {
      title: 'Bachelor of Technology/Engineering',
      nationality: 'Indian',
      gender: 'Any',
    },
    industryType: 'IT-Software Services',
    functionalArea: 'IT-Softwre',
    KeySkills: 'JavaScript,problem solving skills, knowledge of DSA',
    employmenrType: 'Full Time',
    experienceDetails: '5-10 years',
    salary: '100k-200k',
    postedOn: '13 April',
  },
  {
    id: '7',
    employerDetails:
      'is a fast-growing company that relies on emerging technology talent, and we want to give you your first start. BestTech provides all its entry-level software developers with a paid training program to ensure you’ll learn the skills you need to succeed. We offer a flexible schedule and the opportunity to work with some of the industry’s best software developers, either in our Salt Lake City office or remotely across the world. With our wide range of Fortune 500 enterprises as clients, you’ll be working on projects that matter as a part of the BestTech team.',
    title: 'Java Developer',
    location: 'Mumbai',
    vancancy: '1',
    companyName: 'Apex Techno.',
    companyLogo: require('../assets/CompanyLogo/CompanyLogo7.png'),
    jobDescription:
      'We are looking for a great Java developer who is proficient with React.js. Your primary focus will be on developing user interface components and implementing them following well-known React.js workflows (such as Flux or Redux). You will ensure that these components and the overall application are robust and easy to maintain. You will coordinate with the rest of the team working on different layers of the infrastructure. Therefore, a commitment to collaborative problem solving, sophisticated design, and quality product is important.',
    elligibiltyCriteria: {
      title: 'Bachelor of Technology/Engineering',
      nationality: 'Indian',
      gender: 'Any',
    },
    industryType: 'IT-Software Services',
    functionalArea: 'IT-Softwre',
    KeySkills: 'React , Java & TypeScript/JavaScript,Redux,Hooks,Navigations',
    employmenrType: 'Full Time',
    experienceDetails: '5-7 years',
    salary: '100k-200k',
    postedOn: '14 Feb',
  },
  {
    id: '8',
    employerDetails:
      'is a fast-growing company that relies on emerging technology talent, and we want to give you your first start. BestTech provides all its entry-level software developers with a paid training program to ensure you’ll learn the skills you need to succeed. We offer a flexible schedule and the opportunity to work with some of the industry’s best software developers, either in our Salt Lake City office or remotely across the world. With our wide range of Fortune 500 enterprises as clients, you’ll be working on projects that matter as a part of the BestTech team.',
    title: 'Full Stack Developer',
    location: 'Jaipur',
    vancancy: '1',
    companyName: 'Netparam Pvt Ltd.',
    companyLogo: require('../assets/CompanyLogo/CompanyLogo8.jpg'),
    jobDescription:
      'We are looking for a great JavaScript developer who is proficient with React.js. Your primary focus will be on developing user interface components and implementing them following well-known React.js workflows (such as Flux or Redux). You will ensure that these components and the overall application are robust and easy to maintain. You will coordinate with the rest of the team working on different layers of the infrastructure. Therefore, a commitment to collaborative problem solving, sophisticated design, and quality product is important.',
    elligibiltyCriteria: {
      title: 'Bachelor of Technology/Engineering',
      nationality: 'Indian',
      gender: 'Any',
    },
    industryType: 'IT-Software Services',
    functionalArea: 'IT-Softwre',
    KeySkills: 'React Native & TypeScript/JavaScript,Redux,Hooks,Navigations',
    employmenrType: 'Full Time',
    experienceDetails: '0-1 years',
    salary: '100k-200k',
    postedOn: '12 March',
  },
  {
    id: '9',
    employerDetails:
      'is a fast-growing company that relies on emerging technology talent, and we want to give you your first start. BestTech provides all its entry-level software developers with a paid training program to ensure you’ll learn the skills you need to succeed. We offer a flexible schedule and the opportunity to work with some of the industry’s best software developers, either in our Salt Lake City office or remotely across the world. With our wide range of Fortune 500 enterprises as clients, you’ll be working on projects that matter as a part of the BestTech team.',
    title: '.Net Developer',
    location: 'Banglore',
    vancancy: '2',
    companyName: 'Gurukul Softwares.',
    companyLogo: require('../assets/CompanyLogo/CompanyLogo14.png'),
    jobDescription:
      'We are looking for a great Angular developer who is proficient with .Net . Your primary focus will be on developing user interface components and implementing them following well-known React.js workflows (such as Flux or Redux). You will ensure that these components and the overall application are robust and easy to maintain. You will coordinate with the rest of the team working on different layers of the infrastructure. Therefore, a commitment to collaborative problem solving, sophisticated design, and quality product is important.',
    elligibiltyCriteria: {
      title: 'Bachelor of Technology/Engineering',
      nationality: 'Indian',
      gender: 'Any',
    },
    industryType: 'IT-Software Services',
    functionalArea: 'IT-Softwre',
    KeySkills: '.Net & TypeScript,Angular,Redux',
    employmenrType: 'Full Time',
    experienceDetails: '4-5 years',
    salary: '100k-200k',
    postedOn: '11 Jully',
  },
  {
    id: '10',
    employerDetails:
      'is a fast-growing company that relies on emerging technology talent, and we want to give you your first start. BestTech provides all its entry-level software developers with a paid training program to ensure you’ll learn the skills you need to succeed. We offer a flexible schedule and the opportunity to work with some of the industry’s best software developers, either in our Salt Lake City office or remotely across the world. With our wide range of Fortune 500 enterprises as clients, you’ll be working on projects that matter as a part of the BestTech team.',
    title: 'React Developer',
    location: 'Pune',
    vancancy: '2',
    companyName: 'Kongo Techno Pvt Ltd.',
    companyLogo: require('../assets/CompanyLogo/CompanyLogo15.png'),
    jobDescription:
      'We are looking for a great JavaScript developer who is proficient with React.js. Your primary focus will be on developing user interface components and implementing them following well-known React.js workflows (such as Flux or Redux). You will ensure that these components and the overall application are robust and easy to maintain. You will coordinate with the rest of the team working on different layers of the infrastructure. Therefore, a commitment to collaborative problem solving, sophisticated design, and quality product is important.',
    elligibiltyCriteria: {
      title: 'Bachelor of Technology/Engineering',
      nationality: 'Indian',
      gender: 'Any',
    },
    industryType: 'IT-Software Services',
    functionalArea: 'IT-Softwre',
    KeySkills: 'React & TypeScript/JavaScript,Redux,Hooks',
    employmenrType: 'Full Time',
    experienceDetails: '5+ years',
    salary: '100k-200k',
    postedOn: '13 May',
  },
  {
    id: '11',
    employerDetails:
      'is a fast-growing company that relies on emerging technology talent, and we want to give you your first start. BestTech provides all its entry-level software developers with a paid training program to ensure you’ll learn the skills you need to succeed. We offer a flexible schedule and the opportunity to work with some of the industry’s best software developers, either in our Salt Lake City office or remotely across the world. With our wide range of Fortune 500 enterprises as clients, you’ll be working on projects that matter as a part of the BestTech team.',
    title: 'PHP Developer',
    location: 'Pune',
    vancancy: '2',
    companyName: 'Sudoku Pvt Ltd.',
    companyLogo: require('../assets/CompanyLogo/CompanyLogo12.png'),
    jobDescription:
      'We are looking for a great PHP developer who is proficient with React.js. Your primary focus will be on developing user interface components and implementing them following well-known React.js workflows (such as Flux or Redux). You will ensure that these components and the overall application are robust and easy to maintain. You will coordinate with the rest of the team working on different layers of the infrastructure. Therefore, a commitment to collaborative problem solving, sophisticated design, and quality product is important.',
    elligibiltyCriteria: {
      title: 'Bachelor of Technology/Engineering',
      nationality: 'Indian',
      gender: 'Any',
    },
    industryType: 'IT-Software Services',
    functionalArea: 'IT-Softwre',
    KeySkills: 'PHP ',
    employmenrType: 'Full Time',
    experienceDetails: '3 years',
    salary: '100k-200k',
    postedOn: '18 June',
  },
];
